FROM --platform=$BUILDPLATFORM golang:1.24-alpine AS builder
LABEL org.opencontainers.image.source="https://github.com/FIAP-SOAT-G20/hackathon-video-service" \
      org.opencontainers.image.authors="FIAP 10SOAT G21" \
      org.opencontainers.image.title="Fiap X Hackathon Video Service" \
      org.opencontainers.image.description="Image of a backend Video Worker for a Video Service"
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG TARGETOS TARGETARCH
RUN CGO_ENABLED=0 GOOS="$TARGETOS" GOARCH="$TARGETARCH" go build -ldflags "-w -s" -o worker cmd/worker/consumer/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/worker .
CMD ["./worker"]
