// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/cache_middleware_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/cache_middleware_port.go -destination=internal/core/port/mocks/cache_middleware_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheMiddleware is a mock of CacheMiddleware interface.
type MockCacheMiddleware struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMiddlewareMockRecorder
	isgomock struct{}
}

// MockCacheMiddlewareMockRecorder is the mock recorder for MockCacheMiddleware.
type MockCacheMiddlewareMockRecorder struct {
	mock *MockCacheMiddleware
}

// NewMockCacheMiddleware creates a new mock instance.
func NewMockCacheMiddleware(ctrl *gomock.Controller) *MockCacheMiddleware {
	mock := &MockCacheMiddleware{ctrl: ctrl}
	mock.recorder = &MockCacheMiddlewareMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheMiddleware) EXPECT() *MockCacheMiddlewareMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockCacheMiddleware) Add(key string, value any, expire time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", key, value, expire)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockCacheMiddlewareMockRecorder) Add(key, value, expire any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockCacheMiddleware)(nil).Add), key, value, expire)
}

// Decrement mocks base method.
func (m *MockCacheMiddleware) Decrement(key string, data uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrement", key, data)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrement indicates an expected call of Decrement.
func (mr *MockCacheMiddlewareMockRecorder) Decrement(key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrement", reflect.TypeOf((*MockCacheMiddleware)(nil).Decrement), key, data)
}

// Delete mocks base method.
func (m *MockCacheMiddleware) Delete(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheMiddlewareMockRecorder) Delete(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheMiddleware)(nil).Delete), key)
}

// Flush mocks base method.
func (m *MockCacheMiddleware) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockCacheMiddlewareMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockCacheMiddleware)(nil).Flush))
}

// Get mocks base method.
func (m *MockCacheMiddleware) Get(key string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockCacheMiddlewareMockRecorder) Get(key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheMiddleware)(nil).Get), key, value)
}

// Increment mocks base method.
func (m *MockCacheMiddleware) Increment(key string, data uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Increment", key, data)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Increment indicates an expected call of Increment.
func (mr *MockCacheMiddlewareMockRecorder) Increment(key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Increment", reflect.TypeOf((*MockCacheMiddleware)(nil).Increment), key, data)
}

// Replace mocks base method.
func (m *MockCacheMiddleware) Replace(key string, data any, expire time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", key, data, expire)
	ret0, _ := ret[0].(error)
	return ret0
}

// Replace indicates an expected call of Replace.
func (mr *MockCacheMiddlewareMockRecorder) Replace(key, data, expire any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockCacheMiddleware)(nil).Replace), key, data, expire)
}

// Set mocks base method.
func (m *MockCacheMiddleware) Set(key string, value any, expire time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, value, expire)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheMiddlewareMockRecorder) Set(key, value, expire any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheMiddleware)(nil).Set), key, value, expire)
}
