// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/cache_service_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/cache_service_port.go -destination=internal/core/port/mocks/cache_service_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockCacheService is a mock of CacheService interface.
type MockCacheService struct {
	ctrl     *gomock.Controller
	recorder *MockCacheServiceMockRecorder
	isgomock struct{}
}

// MockCacheServiceMockRecorder is the mock recorder for MockCacheService.
type MockCacheServiceMockRecorder struct {
	mock *MockCacheService
}

// NewMockCacheService creates a new mock instance.
func NewMockCacheService(ctrl *gomock.Controller) *MockCacheService {
	mock := &MockCacheService{ctrl: ctrl}
	mock.recorder = &MockCacheServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheService) EXPECT() *MockCacheServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCacheService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacheServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCacheService)(nil).Close))
}

// Delete mocks base method.
func (m *MockCacheService) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheServiceMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheService)(nil).Delete), ctx, key)
}

// Exists mocks base method.
func (m *MockCacheService) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockCacheServiceMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCacheService)(nil).Exists), ctx, key)
}

// Flush mocks base method.
func (m *MockCacheService) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockCacheServiceMockRecorder) Flush(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockCacheService)(nil).Flush), ctx)
}

// Get mocks base method.
func (m *MockCacheService) Get(ctx context.Context, key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheServiceMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheService)(nil).Get), ctx, key)
}

// GetString mocks base method.
func (m *MockCacheService) GetString(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetString indicates an expected call of GetString.
func (mr *MockCacheServiceMockRecorder) GetString(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockCacheService)(nil).GetString), ctx, key)
}

// GetTTL mocks base method.
func (m *MockCacheService) GetTTL(ctx context.Context, key string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTTL", ctx, key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTTL indicates an expected call of GetTTL.
func (mr *MockCacheServiceMockRecorder) GetTTL(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTTL", reflect.TypeOf((*MockCacheService)(nil).GetTTL), ctx, key)
}

// Ping mocks base method.
func (m *MockCacheService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockCacheServiceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockCacheService)(nil).Ping), ctx)
}

// Set mocks base method.
func (m *MockCacheService) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheServiceMockRecorder) Set(ctx, key, value, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheService)(nil).Set), ctx, key, value, expiration)
}

// SetExpiration mocks base method.
func (m *MockCacheService) SetExpiration(ctx context.Context, key string, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExpiration", ctx, key, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExpiration indicates an expected call of SetExpiration.
func (mr *MockCacheServiceMockRecorder) SetExpiration(ctx, key, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpiration", reflect.TypeOf((*MockCacheService)(nil).SetExpiration), ctx, key, expiration)
}

// MockCacheDataSource is a mock of CacheDataSource interface.
type MockCacheDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockCacheDataSourceMockRecorder
	isgomock struct{}
}

// MockCacheDataSourceMockRecorder is the mock recorder for MockCacheDataSource.
type MockCacheDataSourceMockRecorder struct {
	mock *MockCacheDataSource
}

// NewMockCacheDataSource creates a new mock instance.
func NewMockCacheDataSource(ctrl *gomock.Controller) *MockCacheDataSource {
	mock := &MockCacheDataSource{ctrl: ctrl}
	mock.recorder = &MockCacheDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheDataSource) EXPECT() *MockCacheDataSourceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCacheDataSource) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCacheDataSourceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCacheDataSource)(nil).Close))
}

// Delete mocks base method.
func (m *MockCacheDataSource) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCacheDataSourceMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCacheDataSource)(nil).Delete), ctx, key)
}

// DeleteHash mocks base method.
func (m *MockCacheDataSource) DeleteHash(ctx context.Context, key, field string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHash", ctx, key, field)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHash indicates an expected call of DeleteHash.
func (mr *MockCacheDataSourceMockRecorder) DeleteHash(ctx, key, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHash", reflect.TypeOf((*MockCacheDataSource)(nil).DeleteHash), ctx, key, field)
}

// Exists mocks base method.
func (m *MockCacheDataSource) Exists(ctx context.Context, key string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockCacheDataSourceMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockCacheDataSource)(nil).Exists), ctx, key)
}

// Flush mocks base method.
func (m *MockCacheDataSource) Flush(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockCacheDataSourceMockRecorder) Flush(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockCacheDataSource)(nil).Flush), ctx)
}

// Get mocks base method.
func (m *MockCacheDataSource) Get(ctx context.Context, key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCacheDataSourceMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCacheDataSource)(nil).Get), ctx, key)
}

// GetAllHash mocks base method.
func (m *MockCacheDataSource) GetAllHash(ctx context.Context, key string) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHash", ctx, key)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHash indicates an expected call of GetAllHash.
func (mr *MockCacheDataSourceMockRecorder) GetAllHash(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHash", reflect.TypeOf((*MockCacheDataSource)(nil).GetAllHash), ctx, key)
}

// GetHash mocks base method.
func (m *MockCacheDataSource) GetHash(ctx context.Context, key, field string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHash", ctx, key, field)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHash indicates an expected call of GetHash.
func (mr *MockCacheDataSourceMockRecorder) GetHash(ctx, key, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHash", reflect.TypeOf((*MockCacheDataSource)(nil).GetHash), ctx, key, field)
}

// GetList mocks base method.
func (m *MockCacheDataSource) GetList(ctx context.Context, key string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, key)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockCacheDataSourceMockRecorder) GetList(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockCacheDataSource)(nil).GetList), ctx, key)
}

// GetListRange mocks base method.
func (m *MockCacheDataSource) GetListRange(ctx context.Context, key string, start, stop int64) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListRange", ctx, key, start, stop)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListRange indicates an expected call of GetListRange.
func (mr *MockCacheDataSourceMockRecorder) GetListRange(ctx, key, start, stop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListRange", reflect.TypeOf((*MockCacheDataSource)(nil).GetListRange), ctx, key, start, stop)
}

// GetString mocks base method.
func (m *MockCacheDataSource) GetString(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetString", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetString indicates an expected call of GetString.
func (mr *MockCacheDataSourceMockRecorder) GetString(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetString", reflect.TypeOf((*MockCacheDataSource)(nil).GetString), ctx, key)
}

// GetTTL mocks base method.
func (m *MockCacheDataSource) GetTTL(ctx context.Context, key string) (time.Duration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTTL", ctx, key)
	ret0, _ := ret[0].(time.Duration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTTL indicates an expected call of GetTTL.
func (mr *MockCacheDataSourceMockRecorder) GetTTL(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTTL", reflect.TypeOf((*MockCacheDataSource)(nil).GetTTL), ctx, key)
}

// Ping mocks base method.
func (m *MockCacheDataSource) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockCacheDataSourceMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockCacheDataSource)(nil).Ping), ctx)
}

// Set mocks base method.
func (m *MockCacheDataSource) Set(ctx context.Context, key string, value any, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockCacheDataSourceMockRecorder) Set(ctx, key, value, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockCacheDataSource)(nil).Set), ctx, key, value, expiration)
}

// SetAdd mocks base method.
func (m *MockCacheDataSource) SetAdd(ctx context.Context, key string, members ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range members {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetAdd", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAdd indicates an expected call of SetAdd.
func (mr *MockCacheDataSourceMockRecorder) SetAdd(ctx, key any, members ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, members...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAdd", reflect.TypeOf((*MockCacheDataSource)(nil).SetAdd), varargs...)
}

// SetExpiration mocks base method.
func (m *MockCacheDataSource) SetExpiration(ctx context.Context, key string, expiration time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExpiration", ctx, key, expiration)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetExpiration indicates an expected call of SetExpiration.
func (mr *MockCacheDataSourceMockRecorder) SetExpiration(ctx, key, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpiration", reflect.TypeOf((*MockCacheDataSource)(nil).SetExpiration), ctx, key, expiration)
}

// SetHash mocks base method.
func (m *MockCacheDataSource) SetHash(ctx context.Context, key, field string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHash", ctx, key, field, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHash indicates an expected call of SetHash.
func (mr *MockCacheDataSourceMockRecorder) SetHash(ctx, key, field, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHash", reflect.TypeOf((*MockCacheDataSource)(nil).SetHash), ctx, key, field, value)
}

// SetIsMember mocks base method.
func (m *MockCacheDataSource) SetIsMember(ctx context.Context, key string, member any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsMember", ctx, key, member)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIsMember indicates an expected call of SetIsMember.
func (mr *MockCacheDataSourceMockRecorder) SetIsMember(ctx, key, member any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsMember", reflect.TypeOf((*MockCacheDataSource)(nil).SetIsMember), ctx, key, member)
}

// SetList mocks base method.
func (m *MockCacheDataSource) SetList(ctx context.Context, key string, values ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetList", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetList indicates an expected call of SetList.
func (mr *MockCacheDataSourceMockRecorder) SetList(ctx, key any, values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, values...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetList", reflect.TypeOf((*MockCacheDataSource)(nil).SetList), varargs...)
}

// SetMembers mocks base method.
func (m *MockCacheDataSource) SetMembers(ctx context.Context, key string) ([]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMembers", ctx, key)
	ret0, _ := ret[0].([]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMembers indicates an expected call of SetMembers.
func (mr *MockCacheDataSourceMockRecorder) SetMembers(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMembers", reflect.TypeOf((*MockCacheDataSource)(nil).SetMembers), ctx, key)
}
