// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/object_storage_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/object_storage_port.go -destination=internal/core/port/mocks/object_storage_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockObjectStorageDatasource is a mock of ObjectStorageDatasource interface.
type MockObjectStorageDatasource struct {
	ctrl     *gomock.Controller
	recorder *MockObjectStorageDatasourceMockRecorder
	isgomock struct{}
}

// MockObjectStorageDatasourceMockRecorder is the mock recorder for MockObjectStorageDatasource.
type MockObjectStorageDatasourceMockRecorder struct {
	mock *MockObjectStorageDatasource
}

// NewMockObjectStorageDatasource creates a new mock instance.
func NewMockObjectStorageDatasource(ctrl *gomock.Controller) *MockObjectStorageDatasource {
	mock := &MockObjectStorageDatasource{ctrl: ctrl}
	mock.recorder = &MockObjectStorageDatasourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectStorageDatasource) EXPECT() *MockObjectStorageDatasourceMockRecorder {
	return m.recorder
}

// GeneratePresignedDownloadURL mocks base method.
func (m *MockObjectStorageDatasource) GeneratePresignedDownloadURL(ctx context.Context, bucketName, key string, expiration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedDownloadURL", ctx, bucketName, key, expiration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedDownloadURL indicates an expected call of GeneratePresignedDownloadURL.
func (mr *MockObjectStorageDatasourceMockRecorder) GeneratePresignedDownloadURL(ctx, bucketName, key, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedDownloadURL", reflect.TypeOf((*MockObjectStorageDatasource)(nil).GeneratePresignedDownloadURL), ctx, bucketName, key, expiration)
}

// GeneratePresignedURL mocks base method.
func (m *MockObjectStorageDatasource) GeneratePresignedURL(ctx context.Context, bucketName, key string, metadata map[string]string, expiration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, bucketName, key, metadata, expiration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockObjectStorageDatasourceMockRecorder) GeneratePresignedURL(ctx, bucketName, key, metadata, expiration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockObjectStorageDatasource)(nil).GeneratePresignedURL), ctx, bucketName, key, metadata, expiration)
}
