// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/video_gateway_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/video_gateway_port.go -destination=internal/core/port/mocks/video_gateway_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/hackathon-video-service/internal/core/domain/entity"
	valueobject "github.com/FIAP-SOAT-G20/hackathon-video-service/internal/core/domain/value_object"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoGateway is a mock of VideoGateway interface.
type MockVideoGateway struct {
	ctrl     *gomock.Controller
	recorder *MockVideoGatewayMockRecorder
	isgomock struct{}
}

// MockVideoGatewayMockRecorder is the mock recorder for MockVideoGateway.
type MockVideoGatewayMockRecorder struct {
	mock *MockVideoGateway
}

// NewMockVideoGateway creates a new mock instance.
func NewMockVideoGateway(ctrl *gomock.Controller) *MockVideoGateway {
	mock := &MockVideoGateway{ctrl: ctrl}
	mock.recorder = &MockVideoGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoGateway) EXPECT() *MockVideoGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVideoGateway) Create(ctx context.Context, video *entity.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, video)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVideoGatewayMockRecorder) Create(ctx, video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVideoGateway)(nil).Create), ctx, video)
}

// Delete mocks base method.
func (m *MockVideoGateway) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVideoGatewayMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVideoGateway)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockVideoGateway) FindAll(ctx context.Context, customerId uint64, status, statusExclude []valueobject.VideoStatus, hash string, page, limit int, sort string) ([]*entity.Video, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, customerId, status, statusExclude, hash, page, limit, sort)
	ret0, _ := ret[0].([]*entity.Video)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockVideoGatewayMockRecorder) FindAll(ctx, customerId, status, statusExclude, hash, page, limit, sort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockVideoGateway)(nil).FindAll), ctx, customerId, status, statusExclude, hash, page, limit, sort)
}

// FindByID mocks base method.
func (m *MockVideoGateway) FindByID(ctx context.Context, id, userID uint64) (*entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, userID)
	ret0, _ := ret[0].(*entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockVideoGatewayMockRecorder) FindByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockVideoGateway)(nil).FindByID), ctx, id, userID)
}

// Update mocks base method.
func (m *MockVideoGateway) Update(ctx context.Context, video *entity.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, video)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVideoGatewayMockRecorder) Update(ctx, video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVideoGateway)(nil).Update), ctx, video)
}
