// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/video_controller_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/video_controller_port.go -destination=internal/core/port/mocks/video_controller_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	dto "github.com/FIAP-SOAT-G20/hackathon-video-service/internal/core/dto"
	port "github.com/FIAP-SOAT-G20/hackathon-video-service/internal/core/port"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoController is a mock of VideoController interface.
type MockVideoController struct {
	ctrl     *gomock.Controller
	recorder *MockVideoControllerMockRecorder
	isgomock struct{}
}

// MockVideoControllerMockRecorder is the mock recorder for MockVideoController.
type MockVideoControllerMockRecorder struct {
	mock *MockVideoController
}

// NewMockVideoController creates a new mock instance.
func NewMockVideoController(ctrl *gomock.Controller) *MockVideoController {
	mock := &MockVideoController{ctrl: ctrl}
	mock.recorder = &MockVideoControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoController) EXPECT() *MockVideoControllerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVideoController) Create(ctx context.Context, presenter port.Presenter, input dto.CreateVideoInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVideoControllerMockRecorder) Create(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVideoController)(nil).Create), ctx, presenter, input)
}

// Delete mocks base method.
func (m *MockVideoController) Delete(ctx context.Context, presenter port.Presenter, input dto.DeleteVideoInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockVideoControllerMockRecorder) Delete(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVideoController)(nil).Delete), ctx, presenter, input)
}

// Get mocks base method.
func (m *MockVideoController) Get(ctx context.Context, presenter port.Presenter, input dto.GetVideoInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVideoControllerMockRecorder) Get(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVideoController)(nil).Get), ctx, presenter, input)
}

// List mocks base method.
func (m *MockVideoController) List(ctx context.Context, presenter port.Presenter, input dto.ListVideosInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVideoControllerMockRecorder) List(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVideoController)(nil).List), ctx, presenter, input)
}

// Update mocks base method.
func (m *MockVideoController) Update(ctx context.Context, presenter port.Presenter, input dto.UpdateVideoInput) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, presenter, input)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVideoControllerMockRecorder) Update(ctx, presenter, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVideoController)(nil).Update), ctx, presenter, input)
}
