// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/video_usecase_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/video_usecase_port.go -destination=internal/core/port/mocks/video_usecase_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/hackathon-video-service/internal/core/domain/entity"
	dto "github.com/FIAP-SOAT-G20/hackathon-video-service/internal/core/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoUseCase is a mock of VideoUseCase interface.
type MockVideoUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockVideoUseCaseMockRecorder
	isgomock struct{}
}

// MockVideoUseCaseMockRecorder is the mock recorder for MockVideoUseCase.
type MockVideoUseCaseMockRecorder struct {
	mock *MockVideoUseCase
}

// NewMockVideoUseCase creates a new mock instance.
func NewMockVideoUseCase(ctrl *gomock.Controller) *MockVideoUseCase {
	mock := &MockVideoUseCase{ctrl: ctrl}
	mock.recorder = &MockVideoUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoUseCase) EXPECT() *MockVideoUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVideoUseCase) Create(ctx context.Context, input dto.CreateVideoInput) (*entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVideoUseCaseMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVideoUseCase)(nil).Create), ctx, input)
}

// Delete mocks base method.
func (m *MockVideoUseCase) Delete(ctx context.Context, input dto.DeleteVideoInput) (*entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, input)
	ret0, _ := ret[0].(*entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockVideoUseCaseMockRecorder) Delete(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVideoUseCase)(nil).Delete), ctx, input)
}

// Get mocks base method.
func (m *MockVideoUseCase) Get(ctx context.Context, input dto.GetVideoInput) (*entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, input)
	ret0, _ := ret[0].(*entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVideoUseCaseMockRecorder) Get(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVideoUseCase)(nil).Get), ctx, input)
}

// List mocks base method.
func (m *MockVideoUseCase) List(ctx context.Context, input dto.ListVideosInput) ([]*entity.Video, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].([]*entity.Video)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockVideoUseCaseMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVideoUseCase)(nil).List), ctx, input)
}

// Update mocks base method.
func (m *MockVideoUseCase) Update(ctx context.Context, input dto.UpdateVideoInput) (*entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVideoUseCaseMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVideoUseCase)(nil).Update), ctx, input)
}
