// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/port/video_datasource_port.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/port/video_datasource_port.go -destination=internal/core/port/mocks/video_datasource_mock.go
//

// Package mock_port is a generated GoMock package.
package mock_port

import (
	context "context"
	reflect "reflect"

	entity "github.com/FIAP-SOAT-G20/hackathon-video-service/internal/core/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockVideoDataSource is a mock of VideoDataSource interface.
type MockVideoDataSource struct {
	ctrl     *gomock.Controller
	recorder *MockVideoDataSourceMockRecorder
	isgomock struct{}
}

// MockVideoDataSourceMockRecorder is the mock recorder for MockVideoDataSource.
type MockVideoDataSourceMockRecorder struct {
	mock *MockVideoDataSource
}

// NewMockVideoDataSource creates a new mock instance.
func NewMockVideoDataSource(ctrl *gomock.Controller) *MockVideoDataSource {
	mock := &MockVideoDataSource{ctrl: ctrl}
	mock.recorder = &MockVideoDataSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVideoDataSource) EXPECT() *MockVideoDataSourceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVideoDataSource) Create(ctx context.Context, video *entity.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, video)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVideoDataSourceMockRecorder) Create(ctx, video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVideoDataSource)(nil).Create), ctx, video)
}

// Delete mocks base method.
func (m *MockVideoDataSource) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVideoDataSourceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVideoDataSource)(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockVideoDataSource) FindAll(ctx context.Context, filters map[string]any, sort string, page, limit int) ([]*entity.Video, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, filters, sort, page, limit)
	ret0, _ := ret[0].([]*entity.Video)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// FindAll indicates an expected call of FindAll.
func (mr *MockVideoDataSourceMockRecorder) FindAll(ctx, filters, sort, page, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockVideoDataSource)(nil).FindAll), ctx, filters, sort, page, limit)
}

// FindByID mocks base method.
func (m *MockVideoDataSource) FindByID(ctx context.Context, id, userID uint64) (*entity.Video, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id, userID)
	ret0, _ := ret[0].(*entity.Video)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockVideoDataSourceMockRecorder) FindByID(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockVideoDataSource)(nil).FindByID), ctx, id, userID)
}

// Transaction mocks base method.
func (m *MockVideoDataSource) Transaction(ctx context.Context, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transaction", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transaction indicates an expected call of Transaction.
func (mr *MockVideoDataSourceMockRecorder) Transaction(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transaction", reflect.TypeOf((*MockVideoDataSource)(nil).Transaction), ctx, fn)
}

// Update mocks base method.
func (m *MockVideoDataSource) Update(ctx context.Context, video *entity.Video) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, video)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVideoDataSourceMockRecorder) Update(ctx, video any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVideoDataSource)(nil).Update), ctx, video)
}
