// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Checks application readiness",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-check"
                ],
                "summary": "Application Readiness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.HealthCheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/health/livez": {
            "get": {
                "description": "Checks application liveness",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-check"
                ],
                "summary": "Application Liveness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.HealthCheckLivenessResponse"
                        }
                    }
                }
            }
        },
        "/health/readyz": {
            "get": {
                "description": "Checks application readiness",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health-check"
                ],
                "summary": "Application Readiness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.HealthCheckResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.HealthCheckResponse"
                        }
                    }
                }
            }
        },
        "/videos": {
            "get": {
                "description": "List all videos\n## Video list is sorted by:\n- **Status** in **descending** order (CREATED \u003e PROCESSING \u003e FINISHED)\n- **Created date** (CreatedAt) in **ascending** order (oldest first)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "List videos",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by status (Accept many), options: \u003csub\u003eCREATED, PROCESSING, FINISHED\u003c/sub\u003e, ex: \u003csub\u003eCREATED\u003c/sub\u003e or \u003csub\u003eCREATED,PROCESSING\u003c/sub\u003e",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "FAILED",
                        "description": "Exclude by status (Accept many), options: \u003csub\u003eNONE, CREATED, PROCESSING, FINISHED, FAILED\u003c/sub\u003e, ex: \u003csub\u003eFAILED\u003c/sub\u003e (default)",
                        "name": "status_exclude",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by hash",
                        "name": "hash",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "status:d,created_at",
                        "description": "Sort by field (Accept many). Use ` + "`" + `\u003cfield_name\u003e:d` + "`" + ` for descending, and the default order is ascending",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.VideoJsonPaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new video",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Create video",
                "parameters": [
                    {
                        "description": "Video data",
                        "name": "video",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.CreateVideoBodyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/presenter.VideoJsonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    }
                }
            }
        },
        "/videos/{id}": {
            "get": {
                "description": "Search for a video by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Get video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.VideoJsonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update an existing video\nThe status are: **CREATED**, **FAILED**, **PROCESSING**, **FINISHED**\n## Transition of status:\n- CREATED      -\u003e FAILED || PROCESSING\n- FAILED       -\u003e {},\n- PROCESSING   -\u003e FINISHED\n- FINISHED     -\u003e {}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Update video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Video data",
                        "name": "video",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateVideoBodyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.VideoJsonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a video by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Delete video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.VideoJsonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates an existing video\nThe status are: **CREATED**, **FAILED**, **PROCESSING**, **FINISHED**\n## Transition of status:\n- CREATED      -\u003e FAILED || PROCESSING\n- FAILED       -\u003e {},\n- PROCESSING   -\u003e FINISHED\n- FINISHED     -\u003e {}",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Partial update video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Video data",
                        "name": "video",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.UpdateVideoPartilRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/presenter.VideoJsonResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    }
                }
            }
        },
        "/videos/{id}/processed": {
            "get": {
                "description": "Generate a presigned URL to download a processed video from S3\nOnly available for videos with status FINISHED",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "videos"
                ],
                "summary": "Download processed video",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Video ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK - Returns download_url",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "422": {
                        "description": "Video not processed yet",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/middleware.ErrorJsonResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "middleware.ErrorJsonResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "type": "string",
                    "example": "Bad Request"
                }
            }
        },
        "presenter.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 10
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "total_items": {
                    "type": "integer",
                    "example": 1000
                },
                "total_pages": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "presenter.VideoJsonPaginatedResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/presenter.Pagination"
                },
                "videos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/presenter.VideoJsonResponse"
                    }
                }
            }
        },
        "presenter.VideoJsonResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string",
                    "example": "2024-02-09T10:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "This is a description"
                },
                "hash": {
                    "type": "string",
                    "example": "hash_value"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string",
                    "example": "My Video"
                },
                "presigned_url": {
                    "type": "string",
                    "example": "https://s3.amazonaws.com/bucket/video.mp4?signature=..."
                },
                "presigned_url_headers": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    },
                    "example": {
                        "{\"x-amz-meta-user-id\"": " \"1\"}"
                    }
                },
                "status": {
                    "type": "string",
                    "example": "PENDING"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2024-02-09T10:00:00Z"
                },
                "user_id": {
                    "type": "integer",
                    "example": 1
                }
            }
        },
        "request.CreateVideoBodyRequest": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "example": "This is my video description"
                },
                "name": {
                    "type": "string",
                    "example": "My Video"
                }
            }
        },
        "request.UpdateVideoBodyRequest": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "hash": {
                    "type": "string",
                    "example": "abc123hash456"
                },
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/valueobject.VideoStatus"
                        }
                    ],
                    "example": "PROCESSING"
                }
            }
        },
        "request.UpdateVideoPartilRequest": {
            "type": "object",
            "properties": {
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/valueobject.VideoStatus"
                        }
                    ],
                    "example": "PROCESSING"
                }
            }
        },
        "response.HealthCheckLivenessResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "response.HealthCheckResponse": {
            "type": "object",
            "properties": {
                "checks": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/response.HealthCheckVerifications"
                    }
                },
                "status": {
                    "$ref": "#/definitions/response.HealthCheckStatus"
                }
            }
        },
        "response.HealthCheckStatus": {
            "type": "string",
            "enum": [
                "pass",
                "warn",
                "fail"
            ],
            "x-enum-varnames": [
                "HealthCheckStatusPass",
                "HealthCheckStatusWarn",
                "HealthCheckStatusFail"
            ]
        },
        "response.HealthCheckVerifications": {
            "type": "object",
            "properties": {
                "componentId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/response.HealthCheckStatus"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "valueobject.VideoStatus": {
            "type": "string",
            "enum": [
                "CREATED",
                "PROCESSING",
                "FINISHED",
                "FAILED",
                "UNDEFINED"
            ],
            "x-enum-varnames": [
                "CREATED",
                "PROCESSING",
                "FINISHED",
                "FAILED",
                "UNDEFINED"
            ]
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and the access token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "List, create, update and delete videos",
            "name": "videos"
        },
        {
            "description": "Health check",
            "name": "health-check"
        }
    ],
    "externalDocs": {
        "description": "GitHub Repository",
        "url": "https://github.com/FIAP-SOAT-G20/hackathon-video-service"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Hackathon Video Service API",
	Description:      "### FIAP Hackathon - 10SOAT - G21",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
